name: ta_lib
description: A dart version of Ta-Lib.
version: 0.0.1
homepage: https://github.com/JosephusZhou/ta_lib

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
